using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;

// HANDOFF NOTE (Phase 1 - Training Guide):
// New, self-contained script. Does NOT modify HaircutManager, EvaluationSystem, Clipper, Comb, or Brush.
// It only READS HaircutManager.ActiveHairstyle / TrainingMode / TryGetTargetLength(), and optionally
// calls EvaluationSystem.EvaluateActiveHaircut() + GetStage1ZoneScores() for the OPTIONAL zone check.
//
// WHAT THIS DOES:
// Builds an ordered list of training 'steps' (one per hair zone) for whatever haircut is currently
// active on HaircutManager, and lets the player step through them (Next/Previous/GoToStep).
// Each step's tool + instruction text is auto-generated from the zone's real target length, unless
// you've authored an override in styleStepOverrides for that HaircutStyle.
//
// HOW TO WIRE THIS UP IN UNITY (see chat explanation too):
// 1. Create an empty GameObject (e.g. "Training Guide Manager") and add this component.
// 2. Drag your existing HaircutManager into the Haircut Manager field.
// 3. (Optional) Drag your existing EvaluationSystem into the Evaluation System field - only needed
//    if you want the optional 'Check This Zone' button to work.
// 4. Call RefreshStepsForActiveHaircut() whenever a haircut/training mode is chosen - easiest way is
//    to hook it into VRTrainingMenuScreen's existing 'On Start Training' UnityEvent in the Inspector
//    (no code change needed there, that field already exists and is public).
[DisallowMultipleComponent]
public class TrainingGuideManager : MonoBehaviour
{
    [Header("Required Scene Links")]
    [Tooltip("Your existing HaircutManager. Required - this is where target lengths and the active haircut come from.")]
    [SerializeField] private HaircutManager haircutManager;

    [Tooltip("Your existing EvaluationSystem. Optional - only needed for the optional per-zone check.")]
    [SerializeField] private EvaluationSystem evaluationSystem;

    [Tooltip("Your existing CuttingManager (same one Comb/Scissor/Clipper use). Optional - only needed for the 'Reset Combing' precaution button, which snaps every hair card back to its pre-comb pose without touching cut length.")]
    [SerializeField] private CuttingManager cuttingManager;

    [Tooltip("Optional. Assign the same hair cards root your HaircutManager/CuttingManager use. This lets the optional check report counts for the EXACT zone the player is on (e.g. FringeMiddle specifically), not just EvaluationSystem's coarser 7-zone grouping (e.g. all of Fringe/FringeLeft/FringeMiddle/FringeRight combined). Leave empty to search the whole scene instead - works fine, just slower, and only runs when the Check button is pressed.")]
    [SerializeField] private Transform hairCardsRoot;

    [Header("Step Order")]
    [Tooltip("If true, any HaircutStyle without an entry in Style Step Overrides gets an automatically generated step order/tool/instructions from real target lengths. Turn off only if you want to author every single haircut by hand.")]
    [SerializeField] private bool autoGenerateDefaultSteps = true;

    [Tooltip("Optional hand-authored step lists. Only add an entry here if you want to override the auto-generated order/tool/instructions for that specific haircut. Safe to leave empty for now.")]
    [SerializeField] private HaircutStyleStepConfig[] styleStepOverrides;

    [Header("Auto-Generation Tuning")]
    [Tooltip("Zones with a target length at or below this (in cm) are recommended as Clipper steps. Above this, Scissor (with a comb-first note) is recommended. 1.5 cm is a reasonable guard-range cutoff.")]
    [SerializeField] private float clipperVsScissorCutoffCm = 1.5f;

    [Header("Show Cutting Marker (cheat aid)")]
    [Tooltip("Thin red line material drawn across every hair card at its resolved target length. Auto-created (Sprites/Default, red) if left empty.")]
    [SerializeField] private Material cuttingMarkerMaterial;
    [Tooltip("World-space half-width of each red cutting-marker line, in meters - purely visual, roughly matches a single card's width.")]
    [SerializeField] private float cuttingMarkerHalfWidth = 0.018f;
    [Tooltip("World-space thickness of each red cutting-marker line, in meters.")]
    [SerializeField] private float cuttingMarkerLineWidth = 0.0015f;

    [Header("Debug / Current State (read-only at runtime)")]
    [SerializeField] private int currentStepIndex;
    [SerializeField] private List<HairSectionType> activeStepZones = new List<HairSectionType>();

    [Header("Events")]
    [Tooltip("Fires whenever the current step changes (Next/Previous/GoToStep/RefreshStepsForActiveHaircut). Hook your UI panel's refresh method here, or just have the panel poll GetCurrentStepInfo() - both work.")]
    [SerializeField] private UnityEvent<TrainingStepInfo> onStepChanged;

    [Tooltip("Fires after CheckCurrentZoneOptional() runs, with a short human-readable summary.")]
    [SerializeField] private UnityEvent<TrainingZoneCheckResult> onOptionalCheckResult;

    // Barber-flow order: nape/back first, then sides, then crown/top, fringe last.
    // This mirrors HaircutManager's own GetDetailedHairSections() zone set, just reordered for training flow.
    private static readonly HairSectionType[] DefaultZoneOrder = new[]
    {
        HairSectionType.BackNape,
        HairSectionType.BackMiddle,
        HairSectionType.BackUpper,
        HairSectionType.TransitionBackLeftAtMiddleSection,
        HairSectionType.TransitionBackRightAtMiddleSection,
        HairSectionType.TransitionBackLeftAtUpperSection,
        HairSectionType.TransitionBackRightAtUpperSection,
        HairSectionType.LeftSideSideburn,
        HairSectionType.RightSideSideburn,
        HairSectionType.LeftSideUpper,
        HairSectionType.RightSideUpper,
        HairSectionType.CrownBack,
        HairSectionType.CrownLeft,
        HairSectionType.CrownRight,
        HairSectionType.TopLeft,
        HairSectionType.TopMiddle,
        HairSectionType.TopRight,
        HairSectionType.FringeLeft,
        HairSectionType.FringeMiddle,
        HairSectionType.FringeRight,

    };

    private readonly List<TrainingStepInfo> resolvedSteps = new List<TrainingStepInfo>();

    // FEATURE (Show Cutting Marker): a red LineRenderer per hair card, positioned at that card's resolved
    // target length from its root - a direct "cut here" reference the player can toggle on/off, sort of
    // like a cheat code. Rebuilt whenever toggled on or the active haircut changes while already visible.
    private readonly List<LineRenderer> cuttingMarkers = new List<LineRenderer>();
    private Transform cuttingMarkerContainer;
    private bool cuttingMarkersVisible;

    public int CurrentStepIndex => currentStepIndex;
    public int TotalSteps => resolvedSteps.Count;
    public HaircutManager LinkedHaircutManager => haircutManager;
    public bool CuttingMarkersVisible => cuttingMarkersVisible;

    private void Start()
    {
        if (haircutManager != null)
            RefreshStepsForActiveHaircut();
    }

    private void OnDestroy()
    {
        ClearCuttingMarkers();
    }

    // Call from the training guide panel's 'Show Cutting Marker' toggle. Draws/hides a red line on every
    // hair card at its currently-resolved target length (from HaircutManager.TryGetTargetLength), so the
    // player can see exactly where to cut to score marks - purely a visual aid, does not affect cutting.
    public void SetCuttingMarkersVisible(bool visible)
    {
        cuttingMarkersVisible = visible;

        if (visible)
            RebuildCuttingMarkers();
        else
            ClearCuttingMarkers();
    }

    [ContextMenu("Toggle Show Cutting Marker")]
    public void ToggleCuttingMarkersVisible()
    {
        SetCuttingMarkersVisible(!cuttingMarkersVisible);
    }

    // PRECAUTION (Reset Combing): call from the training guide panel's 'Reset Combing' button. Snaps every
    // hair card the comb has ever visually bent back to its exact pre-comb position/rotation/growth
    // direction - it does NOT touch CurrentLength, segment visibility, or anything HaircutManager/
    // EvaluationSystem track, so it's safe to press mid-haircut as a pure "undo the comb's visual drift"
    // safety net if a card ever looks stuck instead of settling back on its own.
    public bool CanResetCombing => cuttingManager != null;

    public void ResetCombedHairToOriginalPose()
    {
        if (cuttingManager == null)
        {
            Debug.LogWarning("[TrainingGuideManager] Reset Combing pressed but no CuttingManager is assigned.");
            return;
        }

        cuttingManager.ResetAllCombedHairCardsToOriginalPose();
    }

    private void RebuildCuttingMarkers()
    {
        ClearCuttingMarkers();

        if (haircutManager == null)
            return;

        if (cuttingMarkerContainer == null)
        {
            GameObject containerObject = new GameObject("Cutting Marker Container (Cheat Aid)");
            containerObject.transform.SetParent(transform, false);
            cuttingMarkerContainer = containerObject.transform;
        }

        Material lineMaterial = ResolveCuttingMarkerMaterial();

        HairCardData[] cards = hairCardsRoot != null
            ? hairCardsRoot.GetComponentsInChildren<HairCardData>(true)
            : FindObjectsOfType<HairCardData>(true);

        for (int i = 0; i < cards.Length; i++)
        {
            HairCardData card = cards[i];

            if (card == null || !haircutManager.TryGetTargetLength(card, out float targetLength, out _))
                continue;

            // Root + growth direction * target length = exactly where the target length says this card
            // should be cut to, regardless of which Target Length Mode currently resolved it.
            Vector3 point = card.GetRootPosition() + card.GetGrowthDirection() * targetLength;
            Vector3 widthAxis = card.transform.right;

            GameObject markerObject = new GameObject("CuttingMarker_" + card.gameObject.name);
            markerObject.transform.SetParent(cuttingMarkerContainer, false);

            LineRenderer line = markerObject.AddComponent<LineRenderer>();
            line.useWorldSpace = true;
            line.positionCount = 2;
            line.material = lineMaterial;
            line.startColor = Color.red;
            line.endColor = Color.red;
            line.startWidth = cuttingMarkerLineWidth;
            line.endWidth = cuttingMarkerLineWidth;
            line.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            line.receiveShadows = false;
            line.SetPosition(0, point - widthAxis * cuttingMarkerHalfWidth);
            line.SetPosition(1, point + widthAxis * cuttingMarkerHalfWidth);

            cuttingMarkers.Add(line);
        }

        Debug.Log($"[TrainingGuideManager] Show Cutting Marker: built {cuttingMarkers.Count} marker(s).");
    }

    private void ClearCuttingMarkers()
    {
        for (int i = 0; i < cuttingMarkers.Count; i++)
        {
            if (cuttingMarkers[i] != null)
                Destroy(cuttingMarkers[i].gameObject);
        }

        cuttingMarkers.Clear();
    }

    private Material ResolveCuttingMarkerMaterial()
    {
        if (cuttingMarkerMaterial != null)
            return cuttingMarkerMaterial;

        Shader shader = Shader.Find("Sprites/Default");
        if (shader == null)
            shader = Shader.Find("Unlit/Color");
        if (shader == null)
            shader = Shader.Find("Standard");

        Material material = new Material(shader);
        material.color = Color.red;
        cuttingMarkerMaterial = material;
        return cuttingMarkerMaterial;
    }

    // Call this whenever the active haircut or training mode changes (e.g. hook into
    // VRTrainingMenuScreen's existing 'On Start Training' UnityEvent - no edit needed there).
    [ContextMenu("Refresh Steps For Active Haircut")]
    public void RefreshStepsForActiveHaircut()
    {
        resolvedSteps.Clear();
        activeStepZones.Clear();

        if (haircutManager == null)
        {
            Debug.LogWarning("[TrainingGuideManager] No HaircutManager assigned - cannot build training steps.");
            return;
        }

        HairSectionType[] zoneOrder = ResolveZoneOrderForActiveHaircut(out TrainingStepDefinition[] overrides);

        for (int i = 0; i < zoneOrder.Length; i++)
        {
            HairSectionType zone = zoneOrder[i];
            TrainingStepDefinition overrideDef = FindOverrideForZone(overrides, zone);
            resolvedSteps.Add(BuildStepInfo(zone, overrideDef, i, zoneOrder.Length));
            activeStepZones.Add(zone);
        }

        currentStepIndex = 0;
        NotifyStepChanged();

        // Keep the cheat-aid markers in sync if the player switches haircuts while they're already on -
        // otherwise they'd keep showing stale target lengths from the previous haircut.
        if (cuttingMarkersVisible)
            RebuildCuttingMarkers();
    }

    public void NextStep()
    {
        if (resolvedSteps.Count == 0)
            return;

        currentStepIndex = Mathf.Min(currentStepIndex + 1, resolvedSteps.Count - 1);
        NotifyStepChanged();
    }

    public void PreviousStep()
    {
        if (resolvedSteps.Count == 0)
            return;

        currentStepIndex = Mathf.Max(currentStepIndex - 1, 0);
        NotifyStepChanged();
    }

    public void GoToStep(int index)
    {
        if (resolvedSteps.Count == 0)
            return;

        currentStepIndex = Mathf.Clamp(index, 0, resolvedSteps.Count - 1);
        NotifyStepChanged();
    }

    public TrainingStepInfo GetCurrentStepInfo()
    {
        if (resolvedSteps.Count == 0)
            return default;

        return resolvedSteps[Mathf.Clamp(currentStepIndex, 0, resolvedSteps.Count - 1)];
    }

    // Phase 2 (Clipper Guard Training): exposes the same guard-rounding logic already used for
    // auto-generated instruction text, so ClipperGuardScorer can compare it against whatever guard
    // the player actually has selected. isClipperStep is false for Scissor steps - guard scoring
    // only makes sense on Clipper steps.
    public float GetRecommendedGuardForCurrentStep(out bool isClipperStep)
    {
        TrainingStepInfo step = GetCurrentStepInfo();
        isClipperStep = step.Tool == RecommendedTool.Clipper;
        return SnapToNearestGuard(step.TargetLengthCm);
    }

    // Optional, non-blocking checkpoint. Does NOT drive the whole guide (per the brief - color/pass-fail
    // feedback here is a bonus check, not the primary teaching mechanism). Uses EvaluationSystem's
    // existing 7-zone Stage1EvaluationZone grouping, so it's coarser than the exact HairSectionType zone
    // the player is currently on - that's expected, it's a 'roughly on track?' sanity check only.
    public TrainingZoneCheckResult CheckCurrentZoneOptional()
    {
        TrainingZoneCheckResult result = default;

        if (resolvedSteps.Count == 0)
        {
            result.HasData = false;
            result.Summary = "No training step loaded yet.";
            onOptionalCheckResult?.Invoke(result);
            return result;
        }

        TrainingStepInfo currentStep = GetCurrentStepInfo();

        // Specific breakdown for the EXACT zone (e.g. FringeMiddle specifically). Reads HairCardData
        // directly, so this works even without an EvaluationSystem linked.
        CountSpecificZoneCards(currentStep.Zone, out int specificTotal, out int specificCorrect, out int specificTooLong, out int specificTooShort);
        result.SpecificZoneTotalCards = specificTotal;
        result.SpecificZoneCorrectCards = specificCorrect;
        result.SpecificZoneTooLongCards = specificTooLong;
        result.SpecificZoneTooShortCards = specificTooShort;

        System.Text.StringBuilder summaryBuilder = new System.Text.StringBuilder();

        if (specificTotal > 0)
        {
            summaryBuilder.Append($"{currentStep.ZoneDisplayName}: {specificCorrect}/{specificTotal} correct ");
            summaryBuilder.Append($"({specificTooLong} too long, {specificTooShort} too short)");
            result.HasData = true;
        }
        else
        {
            summaryBuilder.Append($"{currentStep.ZoneDisplayName}: no hair card data found for this zone yet.");
        }

        // Optional coarser cross-check using EvaluationSystem's existing 7-zone grouping, shown as a
        // second line so both numbers are visible without hiding either one.
        if (evaluationSystem != null)
        {
            evaluationSystem.EvaluateActiveHaircut();
            Stage1EvaluationZone coarseZone = MapToStage1EvaluationZone(currentStep.Zone);
            IReadOnlyList<Stage1ZoneScore> zoneScores = evaluationSystem.GetStage1ZoneScores();

            for (int i = 0; i < zoneScores.Count; i++)
            {
                if (zoneScores[i].Zone != coarseZone)
                    continue;

                result.ZoneScorePercent = zoneScores[i].Score;
                summaryBuilder.Append($"\n{coarseZone} group overall: {zoneScores[i].Score:F0}% ({zoneScores[i].CorrectCards}/{zoneScores[i].TotalCards})");
                break;
            }
        }

        result.Summary = summaryBuilder.ToString();
        onOptionalCheckResult?.Invoke(result);
        return result;
    }

    // Counts HairCardData directly for the EXACT zone (e.g. FringeMiddle only, not the whole Fringe
    // group). Independent of EvaluationSystem - works as long as HaircutManager has applied targets.
    private void CountSpecificZoneCards(HairSectionType zone, out int total, out int correct, out int tooLong, out int tooShort)
    {
        total = 0;
        correct = 0;
        tooLong = 0;
        tooShort = 0;

        HairCardData[] cards = hairCardsRoot != null
            ? hairCardsRoot.GetComponentsInChildren<HairCardData>(true)
            : FindObjectsOfType<HairCardData>(true);

        for (int i = 0; i < cards.Length; i++)
        {
            HairCardData card = cards[i];

            if (card == null || card.Section != zone || !card.HasUsableTargetLength())
                continue;

            total++;
            float tolerance = Mathf.Max(0f, card.TargetTolerance);

            if (card.CurrentLength > card.TargetLength + tolerance)
                tooLong++;
            else if (card.CurrentLength < card.TargetLength - tolerance)
                tooShort++;
            else
                correct++;
        }
    }

    private void NotifyStepChanged()
    {
        onStepChanged?.Invoke(GetCurrentStepInfo());
    }

    private HairSectionType[] ResolveZoneOrderForActiveHaircut(out TrainingStepDefinition[] overrides)
    {
        HaircutStyleStepConfig config = FindStyleConfig(haircutManager.ActiveHairstyle);
        overrides = config != null && config.Steps != null ? config.Steps : System.Array.Empty<TrainingStepDefinition>();

        // The override config supplies per-zone tool/instruction overrides (applied later via
        // FindOverrideForZone) - it does NOT replace the zone order/count itself. Previously this
        // returned ONLY the zones explicitly listed in the override config, meaning authoring even
        // one or two override entries silently discarded every other zone from the training guide
        // entirely. The full default order is always used as the actual step sequence.
        return autoGenerateDefaultSteps ? DefaultZoneOrder : System.Array.Empty<HairSectionType>();
    }

    private HaircutStyleStepConfig FindStyleConfig(HaircutStyle style)
    {
        if (styleStepOverrides == null)
            return null;

        for (int i = 0; i < styleStepOverrides.Length; i++)
        {
            if (styleStepOverrides[i] != null && styleStepOverrides[i].Style == style)
                return styleStepOverrides[i];
        }

        return null;
    }

    private TrainingStepDefinition FindOverrideForZone(TrainingStepDefinition[] overrides, HairSectionType zone)
    {
        if (overrides == null)
            return null;

        for (int i = 0; i < overrides.Length; i++)
        {
            if (overrides[i] != null && overrides[i].Zone == zone)
                return overrides[i];
        }

        return null;
    }

    private TrainingStepInfo BuildStepInfo(HairSectionType zone, TrainingStepDefinition overrideDef, int index, int total)
    {
        TrainingStepInfo info = new TrainingStepInfo
        {
            StepNumber = index + 1,
            TotalSteps = total,
            Zone = zone,
            ZoneDisplayName = ToDisplayName(zone)
        };

        bool hasTarget = haircutManager.TryGetTargetLength(zone, out float targetLength, out _);
        info.HasValidTarget = hasTarget;
        info.TargetLengthMeters = hasTarget ? targetLength : 0f;
        info.TargetLengthDisplayText = hasTarget ? $"{info.TargetLengthCm:0.#} cm" : string.Empty;

        // A blank/unparsable override means "not set" - use the real target length above as normal. A
        // parsed override (single value like "3", or a range like "6 - 8") replaces the displayed target
        // text entirely, and counts as a valid target even if the real HaircutManager data doesn't have
        // one for this zone. The numeric TargetLengthMeters/TargetLengthCm used internally for tool
        // inference and the auto-generated instruction is the range's midpoint.
        if (overrideDef != null && TargetLengthOverrideParser.TryParse(overrideDef.TargetLengthOverrideCm, out float overrideNumericCm, out string overrideDisplayText))
        {
            info.TargetLengthMeters = overrideNumericCm / 100f;
            info.HasValidTarget = true;
            info.TargetLengthDisplayText = overrideDisplayText;
        }

        RecommendedTool tool = overrideDef != null && overrideDef.Tool != RecommendedTool.Any
            ? overrideDef.Tool
            : InferToolFromTargetLength(info.TargetLengthCm);
        info.Tool = tool;

        info.Instruction = overrideDef != null && !string.IsNullOrWhiteSpace(overrideDef.InstructionOverride)
            ? overrideDef.InstructionOverride
            : BuildAutoInstruction(info, index == 0);

        return info;
    }

    private RecommendedTool InferToolFromTargetLength(float targetLengthCm)
    {
        return targetLengthCm <= clipperVsScissorCutoffCm ? RecommendedTool.Clipper : RecommendedTool.Scissor;
    }

    private string BuildAutoInstruction(TrainingStepInfo info, bool isFirstStep)
    {
        string movePhrase = isFirstStep ? $"Start with {info.ZoneDisplayName}" : $"Move to {info.ZoneDisplayName}";

        if (!info.HasValidTarget)
            return $"{movePhrase}. No target length set for this zone yet.";

        string toolPhrase;

        switch (info.Tool)
        {
            case RecommendedTool.Clipper:
                float nearestGuardCm = SnapToNearestGuard(info.TargetLengthCm);
                toolPhrase = $"Use Clipper with roughly a {nearestGuardCm:0.#} cm guard (target {info.TargetLengthDisplayText}).";
                break;

            case RecommendedTool.Comb:
                toolPhrase = $"Comb section flat, target length {info.TargetLengthDisplayText}.";
                break;

            case RecommendedTool.Scissor:
            default:
                toolPhrase = $"Comb section flat, then use Scissor - target length {info.TargetLengthDisplayText}.";
                break;
        }

        return $"{movePhrase}. Clip up all other zones first, then comb this section down before cutting. {toolPhrase} Check length before continuing.";
    }

    // Rounds to the nearest common guard size, purely for display text (Phase 2 will make this a real
    // selectable clipper guard value - see brief). Common guards: 0.5, 1, 1.5, 2, 3 cm.
    private float SnapToNearestGuard(float targetCm)
    {
        float[] guards = { 0.5f, 1f, 1.5f, 2f, 3f };
        float best = guards[0];
        float bestDiff = Mathf.Abs(targetCm - guards[0]);

        for (int i = 1; i < guards.Length; i++)
        {
            float diff = Mathf.Abs(targetCm - guards[i]);

            if (diff < bestDiff)
            {
                bestDiff = diff;
                best = guards[i];
            }
        }

        return best;
    }

    // Simple 'InsertSpaceBeforeCapitals' style formatter, e.g. BackNape -> Back Nape.
    // Deliberately avoids System.Text.RegularExpressions (not needed for this and keeps it simple/cheap).
    private string ToDisplayName(HairSectionType zone)
    {
        string raw = zone.ToString();

        if (string.IsNullOrEmpty(raw))
            return raw;

        System.Text.StringBuilder builder = new System.Text.StringBuilder(raw.Length + 8);
        builder.Append(raw[0]);

        for (int i = 1; i < raw.Length; i++)
        {
            if (char.IsUpper(raw[i]) && !char.IsUpper(raw[i - 1]))
                builder.Append(' ');

            builder.Append(raw[i]);
        }

        return builder.ToString();
    }

    // Mirrors EvaluationSystem.MapToStage1Zone's private grouping logic (7 coarse zones) so the optional
    // check can look up the right Stage1ZoneScore. NOTE: if EvaluationSystem's own mapping ever changes,
    // update this copy too - it is intentionally duplicated here rather than editing EvaluationSystem
    // to add a public version, per the 'don't rewrite existing scripts' rule.
    private Stage1EvaluationZone MapToStage1EvaluationZone(HairSectionType section)
    {
        switch (section)
        {
            case HairSectionType.Fringe:
            case HairSectionType.FringeLeft:
            case HairSectionType.FringeMiddle:
            case HairSectionType.FringeRight:
                return Stage1EvaluationZone.Fringe;

            case HairSectionType.Crown:
            case HairSectionType.CrownBack:
            case HairSectionType.CrownLeft:
            case HairSectionType.CrownRight:
                return Stage1EvaluationZone.Crown;

            case HairSectionType.TopLeft:
            case HairSectionType.TopMiddle:
            case HairSectionType.TopRight:
                return Stage1EvaluationZone.Top;

            case HairSectionType.LeftSide:
            case HairSectionType.LeftSideSideburn:
            case HairSectionType.LeftSideUpper:
            case HairSectionType.TransitionBackLeftAtMiddleSection:
            case HairSectionType.TransitionBackLeftAtUpperSection:
                return Stage1EvaluationZone.LeftSide;

            case HairSectionType.RightSide:
            case HairSectionType.RightSideSideburn:
            case HairSectionType.RightSideUpper:
            case HairSectionType.TransitionBackRightAtMiddleSection:
            case HairSectionType.TransitionBackRightAtUpperSection:
                return Stage1EvaluationZone.RightSide;

            case HairSectionType.BackNape:
                return Stage1EvaluationZone.Nape;

            case HairSectionType.Back:
            case HairSectionType.BackMiddle:
            case HairSectionType.BackUpper:
            default:
                return Stage1EvaluationZone.Back;
        }
    }
}
